Working with Data.Table Package
========================================================
INfo: Written in C, much faster at subsetting


#R's data frame
```{r}
DF=data.frame(x=rnorm(9), y=rep(c("a","b","c"), each=3), z=rnorm(9))
head(DF,3)
```


#R's data Table
```{r}
library(data.table)
DT=data.table(x=rnorm(9), y=rep(c("a","b","c"), each=3), z=rnorm(9))
head(DT,3)
tables()
```
#Subset Data Table
```{r}
DT[,c(2,3)]
DT[,list(mean(x),sum(z))]
DT[,table(y)]
```


#Add new columns
```{r}
DT[,w:=z^2]
DT
```



#Multiple Operations
##First create a temp and perform math on the tmp 
```{r}
DT[,m:={tmp=(x+z);log2(tmp+5)}]
DT
```

#plyr like Operations

```{r}
DT[,a:=x>0]
DT
DT[,b:=mean(x+w), by=a]
DT
```

#Special variables

```{r}
set.seed(100)
DT=data.table(x=sample(letters[1:3],1E5,TRUE))
DT[,.N,by=x]
DT
```

#Keys

```{r}
DT=data.table(x=rep(c("a","b","c"), each=100), y=rnorm(300))
head(DT)
setkey(DT,x)
head(DT)
DT['a']
```


#Joins

```{r}
DT1=data.table(x=c('a','a','b','dt1'), y=1:4)
DT1
DT2=data.table(x=c('a','b','dt2'),z=5:7)
DT2
setkey(DT1,x);setkey(DT2,x)
merge(DT1,DT2)
```


#Fast reading

```{r}
big.df=data.frame(x=rnorm(1e6),y=rnorm(1e6))
file=tempfile()
write.table(big.df, file=file, row.names=FALSE, col.names=TRUE, sep="\t", quote=FALSE)
system.time(fread(file))
```